[build]
  builder = "NIXPACKS"

[[services]]
  name = "calls-tracker"
  source = "calls-tracker"

  [services.deploy]
    startCommand = "npm start"
    restartPolicyType = "ON_FAILURE"
    restartPolicyMaxRetries = 3
